name: Upload to pub.dev on release
on:
  release:
    types: [created]
    tags:
      - 'v*' # Tags starting with 'v'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get package dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
      - name: Publish to pub.dev
        if: startsWith(github.ref, 'refs/tags/v') # only upload tags starting with 'v'
        env:
          PUB_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_PUBLISH_ACCESS_TOKEN }}
        run: dart pub publish --dry-run # remove the '--dry-run' flag when ready to publish
